### PR TITLE
added test_data_location extension to x_trapi

### PR DESCRIPTION
**Pull request by putmantime**
This adds "test_data_location" to the x-trapi extension.
The test data location is a URL to a file in a TRAPI KPs' repository that holds example triples for each triple type in the resource.

### CODE REVIEW

**Comment by colleenXu** [comment]
@putmantime I've assumed that this change has or will be communicated to the rest of Translator?

Currently, this will be optional. All properties are optional except for version at the moment

**Comment by putmantime** [comment]
@colleenXu I was communicating with @newgene about this.  This was initially discussed on the last architecture call and there will be a review and discussion at the next architecture call before it goes to deployment.

**Comment by colleenXu** [comment]
@putmantime @newgene in that case, should I revert the merge? I think it's basically deployed now...

**Comment by putmantime** [comment]
@newgene Please advise.  If I understood correctly it's ok to push it into 'main'. After review and approval, it  will be pushed to the 'production' branch

**Comment by newgene** [comment]
@putmantime @colleenXu yes, merging to `main` is fine, pushing to `production` branch will make it official. Let's discuss it at next arch call.

**Comment by colleenXu** [comment]
@newgene @putmantime

Thank you for making this clearer. I think the main branch is fine right now.

 I was too hasty and pushed the changes to the prod branch. I've now fixed (rebased) the prod branch so that it doesn't have these changes on it. 

I'll wait for people to comment and tell me that these changes are ready for the prod branch...

**Pull request merged**
