### PR TITLE
Add operations list to x-trapi

### PR DESCRIPTION
**Pull request by patrickkwang**

### CODE REVIEW

**Comment by colleenXu** [comment]
We could add an enum with a list of the operations. It looks like the allowed values are bind, fill, filter_results, filter_kgraph, restate, complete_results, filter_results_top_n, filter_kgraph_orphans ?

**Comment by edeutsch** [comment]
I'm pretty sure that list is not yet complete, there are more although I'm hazy on the completeness of the list. I'll ask at today's call.

**Comment by colleenXu** [comment]
@patrickkwang @edeutsch  Should we push this forward without the enum, or add the enum?

**Comment by edeutsch** [comment]
enum is fine if you're willing to update it a few times as we refine the list.

**Comment by colleenXu** [comment]
@newgene What do you think?

**Pull request merged**
