### PR TITLE
operations required. list operation ids as enum

### PR DESCRIPTION
**Pull request by colleenXu**
still unresolved:
* what x-translator and x-trapi properties are required and what aren't

Inspired by #16 

HAS BREAKING SCHEMA CHANGES, so be careful pushing to prod branch

### CODE REVIEW

**Comment by colleenXu** [comment]
@edeutsch please review the following:
* does the TRAPI team / consortium want version, operations, and test_data_location to be required? What about other properties in x-translator (like biolink-version and infores) and x-trapi (asyncquery and the limits)? Related to the current messages in internal Translator Slack, Architecture channel. 
* is the [enum](https://github.com/NCATSTranslator/translator_extensions/blob/b10867c3894066fccf832dc670fc2dabf82d4812/x-trapi/smartapi_x-trapi_schema.json#L32) of operations values correct? I listed the "ids" I saw in the operations.json file.

**Comment by edeutsch** [comment]
> @edeutsch please review the following:
> 
>     * does the TRAPI team / consortium want version, operations, and test_data_location to be required? What about other properties in x-translator (like biolink-version and infores) and x-trapi (asyncquery and the limits)? Related to the current messages in internal Translator Slack, Architecture channel.

My impression is that the mavens of SmartAPI want all these things to be required (and send emails to Translator participants that do not have them) and that the TRAPI team has no opinion either way. I thought we (the TRAPI team) put those things there for you (the SmartAPI team) because you wanted them in everyone's TRAPI/SmartAPI definition file. 

> * is the [enum](https://github.com/NCATSTranslator/translator_extensions/blob/b10867c3894066fccf832dc670fc2dabf82d4812/x-trapi/smartapi_x-trapi_schema.json#L32) of operations values correct? I listed the "ids" I saw in the operations.json file http://standards.ncats.io/operation.json

yes. although subject to change at the whims of the Op & Wf group.

**Comment by edeutsch** [comment]
(I am squirming like the peasant when the king asks the peasant if the taxes should be required)

**Comment by newgene** [comment]
Based on the discussion at this week's architecture meeting, we decided to:

* add `operations` to the required field list.  We have verified that except for two TRAPI entries in SmartAPI, almost all TRAPI entries have `operations` field already:

  [https://smart-api.info/api/query?q=NOT \_exists\_:info.x-trapi.operations AND \_exists\_:info.x-trapi&fields=info&raw=1](https://smart-api.info/api/query?q=NOT%20_exists_:info.x-trapi.operations%20AND%20_exists_:info.x-trapi&fields=info&raw=1)

* remove `test_data_location` from the required field list, and treat it as a recommended field for now.

Either @RichardBruskiewich or @colleenXu, can you please make these changes accordingly, then we can merge this PR.

**Comment by RichardBruskiewich** [comment]
...
> Either @RichardBruskiewich or @colleenXu, can you please make these changes accordingly, then we can merge this PR.

Hi @newgene, I think that @colleenXu now owns the PR in question, so I kindly defer to her on this.

**Comment by colleenXu** [comment]
Noting that I put an enum for the values of operations. This will ideally raise failed-schema-validation for resources that aren't using the actual values for operations...

**Comment by colleenXu** [comment]
noting:
* x-translator.infores still isn't required. 4 resources still don't have that, and I don't know if it makes sense for Utility to have this (like Smartapi Registry itself): https://smart-api.info/api/query?q=NOT%20_exists_:info.x-translator.infores%20AND%20_exists_:info.x-translator&fields=info&raw=1
* x-translator.biolink-model still isn't required. 19 resources don't have that, and I don't know if it makes sense to have this for Utility: https://smart-api.info/api/query?q=NOT%20_exists_:info.x-translator.biolink-version%20AND%20_exists_:info.x-translator&fields=info&size=20&raw=1

**Comment by colleenXu** [comment]
@newgene Just added the new commit, so that test_data_location isn't required

**Comment by colleenXu** [comment]
@newgene is it okay to push these changes to prod? Or keep them on main only for now?

**Pull request merged**
